### ISSUE TITLE
为什么macos不能保存新建的链接

### ISSUE THREAD

**Issue by qian-sam** [d270624/InfluxDB-MacOS-Desktop#2]
首先感谢，这个工具界面很好，也很实用，但是有个问题，为什么macos不能保存新建的链接，一修改或者保存就闪退了。
![image](https://user-images.githubusercontent.com/70569837/101855313-341b2d80-3b9e-11eb-9eed-aaabccb648e3.png)
![image](https://user-images.githubusercontent.com/70569837/101855380-49905780-3b9e-11eb-99a2-78ef230e3b07.png)

Process:               InfluxDBClient [26029]
Path:                  /private/var/folders/*/InfluxDBClient.app/Contents/MacOS/InfluxDBClient
Identifier:            org.pythonmac.unspecified.InfluxDBClient
Version:               0.0.0 (0.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           InfluxDBClient [26029]
User ID:               501

Date/Time:             2020-12-11 10:47:17.676 +0800
OS Version:            Mac OS X 10.15.7 (19H15)
Report Version:        12
Bridge OS Version:     4.6 (17P6610)
Anonymous UUID:        66D26368-3ED4-EAD0

Sleep/Wake UUID:       A2727159-FEBD-4489

Time Awake Since Boot: 180000 seconds
Time Since Wake:       4700 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6b53b33a __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff6b5f7e60 pthread_kill + 430
2   libsystem_c.dylib             	0x00007fff6b4c2808 abort + 120
3   QtCore                        	0x0000000107018989 0x107000000 + 100745
4   QtCore                        	0x000000010701a0d4 QMessageLogger::fatal(char const*, ...) const + 202
5   QtCore.abi3.so                	0x0000000106075e32 pyqt5_err_print() + 802
6   QtCore.abi3.so                	0x000000010607baa4 PyQtSlotProxy::unislot(void**) + 100
7   QtCore.abi3.so                	0x000000010607ba0a PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**) + 58
8   QtCore                        	0x000000010722b2be 0x107000000 + 2273982
9   QtWidgets                     	0x00000001081eea1f 0x1080f4000 + 1026591
10  QtWidgets                     	0x00000001081ee899 0x1080f4000 + 1026201
11  QtWidgets                     	0x00000001081efa4f QAbstractButton::mouseReleaseEvent(QMouseEvent*) + 271
12  QtWidgets.abi3.so             	0x0000000107d679f9 sipQPushButton::mouseReleaseEvent(QMouseEvent*) + 121
13  QtWidgets                     	0x000000010813f7bd QWidget::event(QEvent*) + 445
14  QtWidgets.abi3.so             	0x0000000107d68323 sipQPushButton::event(QEvent*) + 195
15  QtWidgets                     	0x0000000108104fea QApplicationPrivate::notify_helper(QObject*, QEvent*) + 266
16  QtWidgets                     	0x0000000108107ec2 QApplication::notify(QObject*, QEvent*) + 7330
17  QtWidgets.abi3.so             	0x0000000107d8552d sipQApplication::notify(QObject*, QEvent*) + 237
18  QtCore                        	0x00000001071f7d64 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
19  QtWidgets                     	0x0000000108105910 QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 896
20  QtWidgets                     	0x000000010815e99f 0x1080f4000 + 436639
21  QtWidgets                     	0x000000010815d0a5 0x1080f4000 + 430245
22  QtWidgets                     	0x0000000108104fea QApplicationPrivate::notify_helper(QObject*, QEvent*) + 266
23  QtWidgets                     	0x0000000108106476 QApplication::notify(QObject*, QEvent*) + 598
24  QtWidgets.abi3.so             	0x0000000107d8552d sipQApplication::notify(QObject*, QEvent*) + 237
25  QtCore                        	0x00000001071f7d64 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
26  QtGui                         	0x000000010766fca5 QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 3397
27  QtGui                         	0x0000000107654e5b QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 219
28  libqcocoa.dylib               	0x0000000117a3ae00 0x117a01000 + 237056
29  libqcocoa.dylib               	0x0000000117a3b568 0x117a01000 + 238952
30  com.apple.CoreFoundation      	0x00007fff3151cd52 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
31  com.apple.CoreFoundation      	0x00007fff3151ccf1 __CFRunLoopDoSource0 + 103
32  com.apple.CoreFoundation      	0x00007fff3151cb0b __CFRunLoopDoSources0 + 209
33  com.apple.CoreFoundation      	0x00007fff3151b83a __CFRunLoopRun + 927
34  com.apple.CoreFoundation      	0x00007fff3151ae3e CFRunLoopRunSpecific + 462
35  com.apple.HIToolbox           	0x00007fff30147abd RunCurrentEventLoopInMode + 292
36  com.apple.HIToolbox           	0x00007fff301476f4 ReceiveNextEventCommon + 359
37  com.apple.HIToolbox           	0x00007fff30147579 _BlockUntilNextEventMatchingListInModeWithFilter + 64
38  com.apple.AppKit              	0x00007fff2e78d039 _DPSNextEvent + 883
39  com.apple.AppKit              	0x00007fff2e78b880 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
40  com.apple.AppKit              	0x00007fff2ea8def2 -[NSApplication _doModalLoop:peek:] + 315
41  com.apple.AppKit              	0x00007fff2ec2040c __33-[NSApplication runModalSession:]_block_invoke_2 + 69
42  com.apple.AppKit              	0x00007fff2ec203b4 __33-[NSApplication runModalSession:]_block_invoke + 78
43  com.apple.AppKit              	0x00007fff2ea8c4c4 _NSTryRunModal + 100
44  com.apple.AppKit              	0x00007fff2ec202af -[NSApplication runModalSession:] + 128
45  libqcocoa.dylib               	0x0000000117a39a76 0x117a01000 + 232054
46  QtCore                        	0x00000001071f3e0f QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
47  QtCore                        	0x00000001071f8372 QCoreApplication::exec() + 130
48  QtWidgets.abi3.so             	0x0000000107e77352 0x107c39000 + 2351954
49  org.python.python             	0x0000000104b6d93c _PyMethodDef_RawFastCallKeywords + 668
50  org.python.python             	0x0000000104b6cdba _PyCFunction_FastCallKeywords + 42
51  org.python.python             	0x0000000104c2c5ae 0x104b4c000 + 918958
52  org.python.python             	0x0000000104c29560 _PyEval_EvalFrameDefault + 25152
53  org.python.python             	0x0000000104c2d096 _PyEval_EvalCodeWithName + 2422
54  org.python.python             	0x0000000104c23244 PyEval_EvalCode + 100
55  org.python.python             	0x0000000104c2085d 0x104b4c000 + 870493
56  org.python.python             	0x0000000104b6d84e _PyMethodDef_RawFastCallKeywords + 430
57  org.python.python             	0x0000000104b6cdba _PyCFunction_FastCallKeywords + 42
58  org.python.python             	0x0000000104c2c5ae 0x104b4c000 + 918958
59  org.python.python             	0x0000000104c29601 _PyEval_EvalFrameDefault + 25313
60  org.python.python             	0x0000000104b6d1f0 0x104b4c000 + 135664
61  org.python.python             	0x0000000104c2c5bb 0x104b4c000 + 918971
62  org.python.python             	0x0000000104c29601 _PyEval_EvalFrameDefault + 25313
63  org.python.python             	0x0000000104c2d096 _PyEval_EvalCodeWithName + 2422
64  org.python.python             	0x0000000104c23244 PyEval_EvalCode + 100
65  org.python.python             	0x0000000104c60041 PyRun_FileExFlags + 209
66  org.python.python             	0x0000000104c5f8eb PyRun_SimpleFileExFlags + 859
67  org.pythonmac.unspecified.InfluxDBClient	0x000000010000280b 0x100000000 + 10251
68  org.pythonmac.unspecified.InfluxDBClient	0x00000001000011c6 main + 1668
69  org.pythonmac.unspecified.InfluxDBClient	0x0000000100000b20 start + 52

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff6b537882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6b5f8425 _pthread_cond_wait + 698
2   libopenblas.0.dylib           	0x0000000109efa27b 0x109bc1000 + 3379835
3   libsystem_pthread.dylib       	0x00007fff6b5f8109 _pthread_start + 148
4   libsystem_pthread.dylib       	0x00007fff6b5f3b8b thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff6b537882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6b5f8425 _pthread_cond_wait + 698
2   libopenblas.0.dylib           	0x0000000109efa27b 0x109bc1000 + 3379835
3   libsystem_pthread.dylib       	0x00007fff6b5f8109 _pthread_start + 148
4   libsystem_pthread.dylib       	0x00007fff6b5f3b8b thread_start + 15

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff6b537882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6b5f8425 _pthread_cond_wait + 698
2   libopenblas.0.dylib           	0x0000000109efa27b 0x109bc1000 + 3379835
3   libsystem_pthread.dylib       	0x00007fff6b5f8109 _pthread_start + 148
4   libsystem_pthread.dylib       	0x00007fff6b5f3b8b thread_start + 15

Thread 4:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff6b534dfa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6b535170 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff3151cef5 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff3151b9c2 __CFRunLoopRun + 1319
4   com.apple.CoreFoundation      	0x00007fff3151ae3e CFRunLoopRunSpecific + 462
5   com.apple.AppKit              	0x00007fff2e92e954 _NSEventThread + 132
6   libsystem_pthread.dylib       	0x00007fff6b5f8109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6b5f3b8b thread_start + 15

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff6b5f3b68 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff6b5f3b68 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff6b5f3b68 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	0x00007fff6b5f3b68 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff6b5f3b68 start_wqthread + 0

Thread 10:: Dispatch queue: com.apple.libtrace.state.block-list
0   libxpc.dylib                  	0x00007fff6b630234 -[OS_xpc_object dealloc] + 17
1   libsystem_trace.dylib         	0x00007fff6b618baa ___os_state_request_for_self_block_invoke + 928
2   libdispatch.dylib             	0x00007fff6b3996c4 _dispatch_call_block_and_release + 12
3   libdispatch.dylib             	0x00007fff6b39a658 _dispatch_client_callout + 8
4   libdispatch.dylib             	0x00007fff6b39fc44 _dispatch_lane_serial_drain + 597
5   libdispatch.dylib             	0x00007fff6b3a0609 _dispatch_lane_invoke + 414
6   libdispatch.dylib             	0x00007fff6b3a9c09 _dispatch_workloop_worker_thread + 596
7   libsystem_pthread.dylib       	0x00007fff6b5f4a3d _pthread_wqthread + 290
8   libsystem_pthread.dylib       	0x00007fff6b5f3b77 start_wqthread + 15

Thread 11:
0   libsystem_pthread.dylib       	0x00007fff6b5f3b68 start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib       	0x00007fff6b5f3b68 start_wqthread + 0

**Comment by qian-sam** [comment]
版本是1.6的

**Comment by d270624** [comment]
感谢您提出的问题，新版本已修复，请下载1.7版本使用

**Comment by qian-sam** [comment]
谢谢
