### ISSUE TITLE
mac os big sur  11.1无法打开应用

### ISSUE THREAD

**Issue by qian-sam** [d270624/InfluxDB-MacOS-Desktop#3]
这边打不开应用，请帮忙看看
![image](https://user-images.githubusercontent.com/70569837/102857163-e5557980-4462-11eb-9a7e-e4dd098fe557.png)
点不开

**Comment by d270624** [comment]
已经修复，请下载1.8版本测试

**Comment by qian-sam** [comment]
下载了，但是还是闪退

**Comment by qian-sam** [comment]
打开是可以了
