### ISSUE TITLE
1.8的版本在bigsur11.1上还是闪退

### ISSUE THREAD

**Issue by qian-sam** [d270624/InfluxDB-MacOS-Desktop#4]
请帮忙处理下，新建连接，测试成功，保存还是闪退

![image](https://user-images.githubusercontent.com/70569837/103073563-cee62400-4602-11eb-8018-666216c6a290.png)

![image](https://user-images.githubusercontent.com/70569837/103073538-c55cbc00-4602-11eb-8b3d-706c9a6ffe2f.png)

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff20345462 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff20373610 pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff202c6720 abort + 120
3   QtCore                        	0x0000000115a78529 0x115a60000 + 99625
4   QtCore                        	0x0000000115a79c74 QMessageLogger::fatal(char const*, ...) const + 202
5   QtCore.abi3.so                	0x0000000115930857 pyqt5_err_print() + 743
6   QtCore.abi3.so                	0x0000000115936554 PyQtSlotProxy::unislot(void**) + 100
7   QtCore.abi3.so                	0x00000001159364ba PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**) + 58
8   QtCore                        	0x0000000115c8bf6e 0x115a60000 + 2277230
9   QtWidgets                     	0x0000000116fed1df 0x116ef3000 + 1024479
10  QtWidgets                     	0x0000000116fed059 0x116ef3000 + 1024089
11  QtWidgets                     	0x0000000116fee20f QAbstractButton::mouseReleaseEvent(QMouseEvent*) + 271
12  QtWidgets.abi3.so             	0x0000000116b68729 sipQPushButton::mouseReleaseEvent(QMouseEvent*) + 121
13  QtWidgets                     	0x0000000116f3ddfd QWidget::event(QEvent*) + 445
14  QtWidgets.abi3.so             	0x0000000116b6903f sipQPushButton::event(QEvent*) + 191
15  QtWidgets                     	0x0000000116f039ea QApplicationPrivate::notify_helper(QObject*, QEvent*) + 266
16  QtWidgets                     	0x0000000116f06755 QApplication::notify(QObject*, QEvent*) + 6965
17  QtWidgets.abi3.so             	0x0000000116b85db9 sipQApplication::notify(QObject*, QEvent*) + 233
18  QtCore                        	0x0000000115c58a34 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
19  QtWidgets                     	0x0000000116f04310 QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 896
20  QtWidgets                     	0x0000000116f5d022 0x116ef3000 + 434210
21  QtWidgets                     	0x0000000116f5b6e9 0x116ef3000 + 427753
22  QtWidgets                     	0x0000000116f039ea QApplicationPrivate::notify_helper(QObject*, QEvent*) + 266
23  QtWidgets                     	0x0000000116f04e11 QApplication::notify(QObject*, QEvent*) + 497
24  QtWidgets.abi3.so             	0x0000000116b85db9 sipQApplication::notify(QObject*, QEvent*) + 233
25  QtCore                        	0x0000000115c58a34 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
26  QtGui                         	0x0000000116433e2e QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 3534
27  QtGui                         	0x00000001164341b1 QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 4433
28  QtGui                         	0x0000000116418d7b QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 219
29  libqcocoa.dylib               	0x0000000117a59260 0x117a1f000 + 238176
30  libqcocoa.dylib               	0x0000000117a599c8 0x117a1f000 + 240072
31  com.apple.CoreFoundation      	0x00007fff2046ba0c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
32  com.apple.CoreFoundation      	0x00007fff2046b974 __CFRunLoopDoSource0 + 180
33  com.apple.CoreFoundation      	0x00007fff2046b6ef __CFRunLoopDoSources0 + 248
34  com.apple.CoreFoundation      	0x00007fff2046a121 __CFRunLoopRun + 890
35  com.apple.CoreFoundation      	0x00007fff204696ce CFRunLoopRunSpecific + 563
36  com.apple.HIToolbox           	0x00007fff286ee6d0 RunCurrentEventLoopInMode + 292
37  com.apple.HIToolbox           	0x00007fff286ee322 ReceiveNextEventCommon + 283
38  com.apple.HIToolbox           	0x00007fff286ee1ef _BlockUntilNextEventMatchingListInModeWithFilter + 64
39  com.apple.AppKit              	0x00007fff22c86de9 _DPSNextEvent + 883
40  com.apple.AppKit              	0x00007fff22c855af -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1366
41  com.apple.AppKit              	0x00007fff22f5dde9 -[NSApplication _doModalLoop:peek:] + 303
42  com.apple.AppKit              	0x00007fff230e7d79 __33-[NSApplication runModalSession:]_block_invoke_2 + 69
43  com.apple.AppKit              	0x00007fff230e7d21 __33-[NSApplication runModalSession:]_block_invoke + 78
44  com.apple.AppKit              	0x00007fff22f5c3a3 _NSTryRunModal + 100
45  com.apple.AppKit              	0x00007fff230e7c1c -[NSApplication runModalSession:] + 128
46  libqcocoa.dylib               	0x0000000117a57ed6 0x117a1f000 + 233174
47  QtCore                        	0x0000000115c54acf QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
48  QtCore                        	0x0000000115c59042 QCoreApplication::exec() + 130
49  QtWidgets.abi3.so             	0x0000000116c77702 0x116a3b000 + 2344706
50  org.python.python             	0x000000010082193c _PyMethodDef_RawFastCallKeywords + 668
51  org.python.python             	0x0000000100820dba _PyCFunction_FastCallKeywords + 42
52  org.python.python             	0x00000001008e05ae 0x100800000 + 918958
53  org.python.python             	0x00000001008dd560 _PyEval_EvalFrameDefault + 25152
54  org.python.python             	0x00000001008e1096 _PyEval_EvalCodeWithName + 2422
55  org.python.python             	0x00000001008d7244 PyEval_EvalCode + 100
56  org.python.python             	0x00000001008d485d 0x100800000 + 870493
57  org.python.python             	0x000000010082184e _PyMethodDef_RawFastCallKeywords + 430
58  org.python.python             	0x0000000100820dba _PyCFunction_FastCallKeywords + 42
59  org.python.python             	0x00000001008e05ae 0x100800000 + 918958
60  org.python.python             	0x00000001008dd601 _PyEval_EvalFrameDefault + 25313
61  org.python.python             	0x00000001008211f0 0x100800000 + 135664
62  org.python.python             	0x00000001008e05bb 0x100800000 + 918971
63  org.python.python             	0x00000001008dd601 _PyEval_EvalFrameDefault + 25313
64  org.python.python             	0x00000001008e1096 _PyEval_EvalCodeWithName + 2422
65  org.python.python             	0x00000001008d7244 PyEval_EvalCode + 100
66  org.python.python             	0x0000000100914041 PyRun_FileExFlags + 209
67  org.python.python             	0x00000001009138eb PyRun_SimpleFileExFlags + 859
68  org.pythonmac.unspecified.InfluxDBClient	0x000000010000280b 0x100000000 + 10251
69  org.pythonmac.unspecified.InfluxDBClient	0x00000001000011c6 main + 1668
70  org.pythonmac.unspecified.InfluxDBClient	0x0000000100000b20 start + 52

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff203418e2 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff20373e6f _pthread_cond_wait + 1254
2   libopenblas.0.dylib           	0x00000001077d627b 0x10749d000 + 3379835
3   libsystem_pthread.dylib       	0x00007fff20373950 _pthread_start + 224
4   libsystem_pthread.dylib       	0x00007fff2036f47b thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff203418e2 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff20373e6f _pthread_cond_wait + 1254
2   libopenblas.0.dylib           	0x00000001077d627b 0x10749d000 + 3379835
3   libsystem_pthread.dylib       	0x00007fff20373950 _pthread_start + 224
4   libsystem_pthread.dylib       	0x00007fff2036f47b thread_start + 15

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff203418e2 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff20373e6f _pthread_cond_wait + 1254
2   libopenblas.0.dylib           	0x00000001077d627b 0x10749d000 + 3379835
3   libsystem_pthread.dylib       	0x00007fff20373950 _pthread_start + 224
4   libsystem_pthread.dylib       	0x00007fff2036f47b thread_start + 15

Thread 4:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff2033ee7e mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff2033f1f0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2046bbf7 __CFRunLoopServiceMachPort + 316
3   com.apple.CoreFoundation      	0x00007fff2046a2ca __CFRunLoopRun + 1315
4   com.apple.CoreFoundation      	0x00007fff204696ce CFRunLoopRunSpecific + 563
5   com.apple.AppKit              	0x00007fff22e0cc16 _NSEventThread + 124
6   libsystem_pthread.dylib       	0x00007fff20373950 _pthread_start + 224
7   libsystem_pthread.dylib       	0x00007fff2036f47b thread_start + 15

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff2036f458 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff2036f458 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff2036f458 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	0x00007fff2036f458 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff2036f458 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000100d9be00  rcx: 0x00007ffeefbf9fc8  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffeefbf9ff0  rsp: 0x00007ffeefbf9fc8
   r8: 0x00000000000130a8   r9: 0x00007fff889d30e8  r10: 0x0000000100d9be00  r11: 0x0000000000000246
  r12: 0x0000000000000307  r13: 0x00000001176a7af0  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007fff20345462  rfl: 0x0000000000000246  cr2: 0x0000000115a7cc90
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

**Comment by d270624** [comment]
我在11.1上测试没有问题啊，我重新打了一下1.8的包，你再重新下载试试。
可以把文件换个目录打开看看

**Comment by qian-sam** [comment]
搞定了，感谢，我放在了下载目录了

**Comment by d270624** [comment]
👌
