### ISSUE TITLE
mac系统打开，添加连接，直接崩溃

### ISSUE THREAD

**Issue by huchunyong1987** [d270624/InfluxDB-MacOS-Desktop#9]
mac系统打开，添加连接，直接崩溃
![image](https://user-images.githubusercontent.com/41766973/145971273-e48ad2bd-5e53-4f6d-8fe4-31a004d54c00.png)
![image](https://user-images.githubusercontent.com/41766973/145971216-a0236a3f-2a92-4a9e-90c0-994b37d50b1e.png)

**Comment by d270624** [comment]
重新发了一版，再试试吧。而且我之前开发用的电脑，系统就是这个版本，可以正常运行啊。
